### ISSUE TITLE
Not working, what can i troubleshoot? "LOGIN_DISABLED"

### ISSUE THREAD

**Issue by balajeek** [danricho/where_the#18]
I followed the docker-compose method.
1. got from git
2. created config as described (changed user/password)
3. created data.json file as described
4. I changed the port to 5065:5000 in docker-compose (because i have something jackett running on 5055)

ran docker-compose and the web site not up, log shows this:

```
Traceback (most recent call last):
  File "/srv/main.py", line 57, in <module>
    app.config['LOGIN_DISABLED'] = config['FLASK']['LOGIN_DISABLED'] 
KeyError: 'LOGIN_DISABLED'
```

I opened the config and changed the AUTHENTICATION: NO-AUTH and i still get the same error and it keeps repeating every min.

What can i do?

**Comment by pjfian** [comment]
Looks like you might be using the current config, but with an older commit
version.

Try re-cloning from github.

**Comment by danricho** [comment]
Yes, one of the changes to support the different authentication methods the required config changed. If you have a look at the readme, there is a section of the config which you will need to adjust yours to. 

If you have already done that, you likely just need to update your version as @pjfian mentioned... there is also a section of the readme concerning that.

**Comment by balajeek** [comment]
I tried git pull and recreated the container, no luck
So i deleted everything including the where_the folder, did git pull and used the same config.yml which i backed up before deleting.  started the container and i still get exactly the same error!

**Comment by danricho** [comment]
I'm not sure how that can happen as the latest version of the `main.py` file doesn't include the line your error is identifying.

It's possible something is going on with the docker container as I don't run the docker container day to day.

I will try to recreate this problem when I'm next at my computer.

Would you be willing to share your config file and the top entry in your `git log` as it sounds like it isn't getting the latest version from GitHub for some reason.

**Comment by balajeek** [comment]
here is the config;

```
AUTHELIA-LOGOUT: https://auth.SAMPLE-DOMAIN.org
AUTHENTICATION: NO-AUTH
FLASK:
  DEBUG: false
  HOST: 192.168.1.13
  PORT: '5000'
  SECRET: passtest#
  TEMPLATES_AUTO_RELOAD: true
  USE_RELOADER: false
PRIMARY-COLOR: '#C0A890'
PRINT_TEMPLATE:
  ADD_DESCRIPTION_TO_LABEL: true
  ADD_LOGO_TO_QR: true
  COLORED_BACKGROUNDS: true
  DESCRIPTION_FONT_SIZE: 0.35cm
  IDENTIFIER: AVERY L7164
  ID_FONT_SIZE: 0.8cm
  LABEL:
    HEIGHT: 7.2cm
    WIDTH: 6.353cm
    X_GUTTER: 0.25cm
    X_PADDING: 0.25cm
    Y_GUTTER: 0cm
    Y_PADDING: 0.1cm
  LABELS_PER_PAGE: 12
  PAGE:
    WIDTH: 21cm
    X_MARGIN: 0.7214cm
    Y_MARGIN: 0.457cm
  QR_HEIGHT: 4.3cm
SITE:
  BASE_URL: http://192.168.1.13
  PATH_PREFIX: /
USERS: {}
```

git log:

```
$:~/docker$ git clone https://github.com/danricho/where_the.git where_the
Cloning into 'where_the'...
remote: Enumerating objects: 290, done.
remote: Counting objects: 100% (290/290), done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 290 (delta 189), reused 212 (delta 111), pack-reused 0
Receiving objects: 100% (290/290), 2.06 MiB | 16.39 MiB/s, done.
Resolving deltas: 100% (189/189), done.
```

**Comment by danricho** [comment]
Could you also run the command `git log` and share first entry?

**Comment by danricho** [comment]
My attempt to reproduce:

Clone from GitHub and revert to newest version with line in your error at 57 in `main.py` (commit: 9dcd256):
```bash
 $ git clone https://github.com/danricho/where_the.git
 $ cd where_the/
 $ git reset --hard 9dcd256
```

Added following `config.yml` (compatible with the version at 8b4c81e1) and blank `data.json`
```yaml
FLASK:
  DEBUG: false
  HOST: 0.0.0.0
  LOGIN_DISABLED: true
  PORT: '5000'
  SECRET: abcd1234
  TEMPLATES_AUTO_RELOAD: true
  USE_RELOADER: false
PRIMARY-COLOR: '#C0A890'
PRINT_TEMPLATE:
  ADD_DESCRIPTION_TO_LABEL: true
  ADD_LOGO_TO_QR: true
  DESCRIPTION_FONT_SIZE: 0.35cm
  IDENTIFIER: AVERY L7164
  ID_FONT_SIZE: 0.8cm
  LABEL:
    HEIGHT: 7.2cm
    WIDTH: 6.353cm
    X_GUTTER: 0.25cm
    X_PADDING: 0.25cm
    Y_GUTTER: 0cm
    Y_PADDING: 0.1cm
  LABELS_PER_PAGE: 12
  PAGE:
    WIDTH: 21cm
    X_MARGIN: 0.7214cm
    Y_MARGIN: 0.457cm
  QR_HEIGHT: 4.3cm
SITE:
  BASE_URL: http://localhost:5055
  PATH_PREFIX: /
USERS: # THIS ONLY APPLIES IF FLASK.LOGIN_DISABLED == FALSE...
  1:
    password: pass
    username: user
  2:
    password: pass
    username: user2
```
Brought up via docker-compose (extra flags to force a fresh docker image build)

```bash
$ docker-compose up -d --force-recreate --build
```

At this stage I have an environment which is working with the old `config['FLASK']['LOGIN_DISABLED']` config value working - I verified by changing this value from false to true... login not required when true.

Now to change to the new version and see what happens...

```bash
$ git pull
```

This reports a move to the newest commit as shown in GitHub (effad56). 

If I now rebuild and run the docker image, I get the following error in the docker logs (as expected because I haven't change the config yet).

```text
Traceback (most recent call last):
  File "/srv/main.py", line 60, in <module>
    app.config['LOGIN_DISABLED'] = (config['AUTHENTICATION'] not in ["FLASK-LOGIN", "AUTHELIA"])
KeyError: 'AUTHENTICATION'
```

To fix this, I remove `LOGIN_DISABLED: true` in the `FLASK` section and add the following:

```yaml
AUTHENTICATION: FLASK-LOGIN 
USERS: {} # CHANGED TO THIS BECAUSE NO-AUTH
```

**It's working at this stage with the current version.**
